"""empty message

Revision ID: 1989208b19e3
Revises: 49a7ddcc21ac
Create Date: 2020-10-01 17:26:22.591361

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1989208b19e3'
down_revision = '49a7ddcc21ac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tags',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created', sa.DateTime(timezone=True), nullable=False),
    sa.Column('name', sa.Unicode(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('feedback_tag_association',
    sa.Column('feedback_id', sa.Integer(), nullable=True),
    sa.Column('tag_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['feedback_id'], ['feedback.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('feedback_tag_association')
    op.drop_table('tags')
    # ### end Alembic commands ###
