"""empty message

Revision ID: 49a7ddcc21ac
Revises: 2163609534a3
Create Date: 2020-09-07 12:07:11.606621

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49a7ddcc21ac'
down_revision = '2163609534a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('parse_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created', sa.DateTime(timezone=True), nullable=False),
    sa.Column('nl', sa.Unicode(length=500), nullable=False),
    sa.Column('lin', sa.Unicode(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('parse_logs')
    # ### end Alembic commands ###
