"""Add feedback_states table

Revision ID: e1205998b3e7
Revises: 24d13b5fabeb
Create Date: 2021-01-03 17:29:43.331352

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e1205998b3e7'
down_revision = '24d13b5fabeb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feedback_states',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created', sa.DateTime(timezone=True), nullable=False),
    sa.Column('feedback_id', sa.Integer(), nullable=False),
    sa.Column('model', sa.Unicode(length=500), nullable=False),
    sa.Column('correct', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('feedback_states')
    # ### end Alembic commands ###
